# Generated by Django 3.2.9 on 2021-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_text', models.CharField(max_length=50)),
                ('last_name_text', models.CharField(max_length=50)),
            ],
        ),
    ]
